//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Okul_Otomasyon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Okul_otomasyonEntities : DbContext
    {
        public Okul_otomasyonEntities()
            : base("name=Okul_otomasyonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ilceler> ilceler { get; set; }
        public virtual DbSet<iller> iller { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_brans> tbl_brans { get; set; }
        public virtual DbSet<tbl_ogrenciler> tbl_ogrenciler { get; set; }
        public virtual DbSet<tbl_ogretmenler> tbl_ogretmenler { get; set; }
        public virtual DbSet<veliler> veliler { get; set; }
    }
}
