//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Okul_Otomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class veliler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public veliler()
        {
            this.tbl_ogrenciler = new HashSet<tbl_ogrenciler>();
        }
    
        public int id { get; set; }
        public string anne { get; set; }
        public string baba { get; set; }
        public string tel1 { get; set; }
        public string tel2 { get; set; }
        public string mail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ogrenciler> tbl_ogrenciler { get; set; }
    }
}
